org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_base_version=1.20
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.6
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=storagedrawersextra
mod_name=Storage Drawers Extras
mod_filename=StorageDrawersExtras
mod_license=MIT
mod_version=12.1.0
mod_group_id=com.texelsaur.minecraft.storagedrawersextra
mod_authors=Texelsaur
mod_description=Additional wood variants for Storage Drawers
storagedrawers_range=[12.11,13)

# Mod dependency versions
jei_version=11.5.0.297
jei_id=4644453
storagedrawers_projid=223852
storagedrawers_fileid=6858071

# Supported content mods
biomesoplenty_projid=220318
biomesoplenty_fileid=4764804
immersiveeng_projid=231951
immersiveeng_fileid=5224387
biomeswevegone_projid=1070751
biomeswevegone_fileid=5574092

# Extended required dependencies
terrablender_projid=563928
terrablender_fileid=5378180
ohthetreesyoullgrow_projid=962544
ohthetreesyoullgrow_fileid=5396845
corgilib_projid=693313
corgilib_fileid=5436749
geckolib_projid=388172
geckolib_fileid=5460309
