org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_base_version=1.20
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=storagedrawersextra
mod_name=Storage Drawers Extras
mod_license=MIT
mod_version=12.0.0
mod_group_id=com.texelsaur.minecraft.storagedrawersextra
mod_authors=Texelsaur
mod_description=Additional wood variants for Storage Drawers
storagedrawers_range=[12.5,13)

# Mod dependency versions
jei_version=11.5.0.297
jei_id=4644453
storagedrawers_projid=223852
storagedrawers_fileid=5631332

# Supported content mods
biomesoplenty_projid=220318
biomesoplenty_fileid=4764804
terrablender_projid=563928
terrablender_fileid=5068218